#cloud-config
# ssh keys for access
ssh_authorized_keys:
- github:scottcramer
#- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDERWzWhJ0Wc7fRdq8Wy9GDzrW6Piza55+I/y/33oEwuAZ+JLfnfVxbUJMN+EvXPNDavZVOTx7uda9r7saGUz3We0yf6IJ/mv/kbALKoKep0s/xN8EUmgPXAmbP6YjcaYrm3yXaBv8o5Fzt9bQ262UNRC6IyyIn+AdU8UYK4fwhWF6RpeDJVQILd3RyNAie9wFsPhVIuMj3DfjtUpo4bsDOFzxJSqUzTJie9MehynUA+Eb8lNiNUYltwrsddrBXHCm3tqhhkmUGu5BBnReXbnAsb4VHnas22mNT66anICxlSS7efccxa+74VsRDN5fnR0sRGEzNl+4R2mW0jNUshfvuUNiskaFldDWIJSxbjTAZOX1rl34aYugUWb803OXNhhdZovlCHtXA/yJHmY8pjYicAKZw2DKwuDvtocJTkyNBCBoa0yI4/wbHWKCQcnfh0Vpo3vTZfQsVfYNzBIvJzR1H7a4Hz1iGBUNHtlKBsaALv5zg+fLj+VOoDarA4Waf3vI2q6tvx4OhjRh804r01aiwBnhVpIwTscZRALDTcYNhFTzY46VOCXPfW+v/MY/lae66PdDHhBH9JGW2iW3NsiRSbyPCCQ5GCNfHGYSIIgFB6JwWJjLlu9K6XS6NRaBtTzIlXIcG9IIWuK7ul9TjaaxIu4CuDRQTGpUNy3YaQWKICQ==

# rancherOS hostname
hostname: k3os-node-2  

# rancher-network settings
k3os:
  network:
    interfaces:
      eth0:
        dhcp: true
        mtu: 1500
  server_url: https://k3os-master:6443/
  token: 1GVQbH7SGp7wZXUA5r
  k3s_args:
  - server
  environment:
    K3S_KUBECONFIG_MODE: 644