#cloud-config
# ssh keys for access
ssh_authorized_keys:
- github:scottcramer

# rancherOS hostname
hostname: k3os-master   

# rancher-network settings
k3os:
  network:
    interfaces:
      eth0:
        dhcp: true
        mtu: 1500
#  server_url: https://k3os-master/
  token: 1GVQbH7SGp7wZXUA5r
  k3s_args:
  - server
  environment:
    K3S_KUBECONFIG_MODE: 644
